version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run export

artifacts:
  files:
    - '**/*'
  base-directory: out
