import type { Metadata } from "next";
import { Cairo, Inter } from "next/font/google";
import "./globals.css";



const inter = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        {children}
        
        
        </body>
    </html>
  );
}
